aoshidostudy_index:
    path:     /
    defaults: { _controller: AoshidostudyBundle:Default:index }
    
preguntas_ABM:
    path:     /preguntas/abm
    defaults: { _controller: AoshidostudyBundle:Default:abmPreguntas }
    
preguntas_QUIZ:
    path:     /preguntas/quiz
    defaults: { _controller: AoshidostudyBundle:Default:quizPreguntas }
