aoshidostudy_hello:
    path:     /hello/{name}
    defaults: { _controller: AoshidostudyBundle:Default:index }
    
aoshidostudy_homepage:
    path:     /
    defaults: { _controller: AoshidostudyBundle:Default:homepage }
