aoshidostudy_index:
    path:     /
    defaults: { _controller: AoshidostudyBundle:Default:index }
    
preguntas_ABM:
    path:     /preguntas/abm
    defaults: { _controller: AoshidostudyBundle:Default:abmPreguntas }
    
preguntas_EDIT:
    path:     /preguntas/abm/edit/{id}
    defaults: { _controller: AoshidostudyBundle:Default:editPreguntas }

preguntas_DELETE:
    path:     /preguntas/abm/delete/{id}
    defaults: { _controller: AoshidostudyBundle:Default:deletePreguntas }
    
preguntas_QUIZ:
    path:     /preguntas/quiz
    defaults: { _controller: AoshidostudyBundle:Default:quizPreguntas }

preguntas_CARDS:
    path:     /preguntas/cards
    defaults: { _controller: AoshidostudyBundle:Default:cardsIndex }