parameters:
#    aoshidostudy.example.class: Aoshido\studyBundle\Example

services:
#    aoshidostudy.example:
#        class: %aoshidostudy.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
